### ISSUE TITLE
Crash on iPhone Xs Max, iOS 12.0

### ISSUE THREAD

**Issue by young-hnau** [Alticha/alticha.github.io#2]
When I open the app I see a white screen which lasts for about 30 seconds before rebooting my entire phone. I have the same issue on 2017 iPad Pro 12.9", iOS 12.0, although I have gotten it to succeed twice after numerous attempts (only succeeds on iPad). I never see the actual screen allowing me to change the badge colors.

**Comment by Alticha** [comment]
patchfinder64 is broken on A12

**Comment by Alticha** [comment]
fixed
